# Import libraries

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/racs/scikitlearn/tasvmc/1/SVM_model.joblib
/kaggle/input/arabic-classification/arabic_dataset_classifiction.csv/arabic_dataset_classifiction.csv


In [3]:
pip install  nltk


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 17.1 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [4]:
#import librares 
import os 
import random
import re 
import string 
import numpy as np 
import pandas as pd 
import nltk


In [5]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize ,RegexpTokenizer
from nltk.stem.isri import ISRIStemmer


In [6]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [7]:
from sklearn.model_selection import train_test_split 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.svm import  SVC
from joblib import dump, load
from sklearn.metrics import accuracy_score

# Read dataset 

In [8]:
data= pd.read_csv("/kaggle/input/arabic-classification/arabic_dataset_classifiction.csv/arabic_dataset_classifiction.csv")

In [9]:
data.head()

text  targe
0  بين أستوديوهات ورزازات وصحراء مرزوكة وآثار ولي...      0
1  قررت النجمة الأمريكية أوبرا وينفري ألا يقتصر ع...      0
2  أخبارنا المغربية الوزاني تصوير الشملالي ألهب ا...      0
3  اخبارنا المغربية قال ابراهيم الراشدي محامي سعد...      0
4  تزال صناعة الجلود في المغرب تتبع الطريقة التقل...      0

# Data cheaking 

In [10]:
data.isnull().sum()

text     2939
targe       0
dtype: int64

In [11]:
clean_data= data.dropna()

In [12]:
clean_data.isnull().sum()

text     0
targe    0
dtype: int64

In [13]:
#show thw text 
clean_data.iloc[0,0]

'بين أستوديوهات ورزازات وصحراء مرزوكة وآثار وليلي ثم الرباط والبيضاء انتهى المخرج المغربي سهيل بن بركة من تصوير مشاهد عمله السينمائي الجديد الذي خصصه لتسليط الضوء عن حياة الجاسوس الإسباني دومينغو باديا الذي عاش فترة من القرن التاسع عشر بالمغرب باسم علي باي هذا الفيلم الذي اختار له مخرجه عنوان حلم خليفة يصور حياة علي باي العباسي الذي ما زال أحد أحياء طنجة يحمل اسمه عاش حياة فريدة متنكرا بشخصية تاجر عربي من سلالة الرسول صلى الله عليه وسلم فيما كان يعمل جاسوسا لحساب إسبانيا وكشف مخرج الفيلم سهيل بن بركة في تصريح لهسبريس أن الفيلم السينمائي دخل مرحلة التوضيب التي تتم خارج المغرب مبرزا أن الفيلم الذي يروي حياة الجاسوس الإسباني دومينغو باديا منذ أن قرر من طنجة بدء رحلاته نحو عدد من المناطق في العالم الإسلامي بداية القرن العشرين سيكون جاهزا بعد شهرين ويجمع الفيلم السينمائي عددا من الممثلين من مختلف الجنسيات واختار لدور البطولة الممثلة السينمائية الإيطالية كارولينا كريشنتيني للقيام بدور الإنجليزية الليدي هستر ستانهوب التي اشتهرت في الكتب الغربية بـ زنوبيا والتي عاشت بدورها بالدول العربية وارتب

In [14]:
#show label 
clean_data.iloc[0,1]

0

# Data cleaing 

In [15]:
#remove some marks 
# sampl=r'#.][!XR'

# for letter in r'#.][!XR':
#     clean_data['text'] = clean_data['text'].astype(str).str.replace(letter,'',regex=True)
for letter in r'#.][!XR':
    clean_data['text'] = clean_data['text'].astype(str).str.replace(re.escape(letter), '', regex=True)


/tmp/ipykernel_13/1317373425.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_data['text'] = clean_data['text'].astype(str).str.replace(re.escape(letter), '', regex=True)
/tmp/ipykernel_13/1317373425.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_data['text'] = clean_data['text'].astype(str).str.replace(re.escape(letter), '', regex=True)
/tmp/ipykernel_13/1317373425.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexe

In [16]:
english_punc = string.punctuation
arabic_punc = '''`÷×؛<>_()*&^%][ـ،/:"؟.,'{}~¦+|!”…“–ـ'''
all_punc= english_punc + arabic_punc 
all_punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~`÷×؛<>_()*&^%][ـ،/:"؟.,\'{}~¦+|!”…“–ـ'

In [17]:
def remove_punc (text): 
    translator = str.maketrans('','',all_punc)
    return text.translate(translator)

In [18]:
import re
def remove_repeating_char(text):
    return re.sub(r'(.)\1+',r'\1',text)
# هيبحث عن . الكثيرة في النص ز يسنبديها ب . واحدة فقط 
# .................... -> .

In [19]:
def normalize_arabic (text):
    text = re.sub("[إأآا]",  "ا", text)
    text = re.sub("ى", "ي", text)
    text = re.sub("ة", "ه",text)
    text = re.sub("گ", "ك",text)
    return text
############## گ ف النص هنستبدل ال ك ب 

In [20]:
stemmer = ISRIStemmer()

In [21]:
def processDoc(doc, stemmer):
    doc = remove_punc(doc)
    doc = re.sub(r'@[^\s]+', ' ', doc)
    doc = re.sub(r'_', ' ', doc)
    doc = re.sub(r'\n', ' ', doc)
    doc = re.sub(r'[a-z,A-Z]', '', doc)
    doc = re.sub(r'\d', '', doc)
    doc = re.sub('((www\.[^\s]+)|(https?://[^\s]+))',' ',doc)
    doc = normalize_arabic ( doc)
    doc = remove_repeating_char (doc)
    
    doc = stemmer.stem(doc)
    
    return doc

In [22]:
l=processDoc(clean_data.iloc[0,0],stemmer)

In [23]:
l

'بين استوديوهات ورزازات وصحراء مرزوكه واثار وليلي ثم الرباط والبيضاء انتهي المخرج المغربي سهيل بن بركه من تصوير مشاهد عمله السينمائي الجديد الذي خصه لتسليط الضوء عن حياه الجاسوس الاسباني دومينغو باديا الذي عاش فتره من القرن التاسع عشر بالمغرب باسم علي باي هذا الفيلم الذي اختار له مخرجه عنوان حلم خليفه يصور حياه علي باي العباسي الذي ما زال احد احياء طنجه يحمل اسمه عاش حياه فريده متنكرا بشخصيه تاجر عربي من سلاله الرسول صلي اله عليه وسلم فيما كان يعمل جاسوسا لحساب اسبانيا وكشف مخرج الفيلم سهيل بن بركه في تصريح لهسبريس ان الفيلم السينمائي دخل مرحله التوضيب التي تم خارج المغرب مبرزا ان الفيلم الذي يروي حياه الجاسوس الاسباني دومينغو باديا منذ ان قر من طنجه بدء رحلاته نحو عد من المناطق في العالم الاسلامي بدايه القرن العشرين سيكون جاهزا بعد شهرين ويجمع الفيلم السينمائي عدا من المثلين من مختلف الجنسيات واختار لدور البطوله المثله السينمائيه الايطاليه كارولينا كريشنتيني لقيام بدور الانجليزيه اليدي هستر ستانهوب التي اشتهرت في الكتب الغربيه ب زنوبيا والتي عاشت بدورها بالدول العربيه وارتبطت بعلي باي

In [24]:
clean_data['text']= clean_data['text'].apply(lambda x : processDoc(x,stemmer))

/tmp/ipykernel_13/1527429073.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_data['text']= clean_data['text'].apply(lambda x : processDoc(x,stemmer))


In [25]:
clean_data.iloc[3787,0]

'اخبارنا المغربيه حنان سلامه اكدت الفنانه الصحراويه المغربيه سعيده شرف قبل قليل ان زوجها قد تعرض لحادثه سير خطيره داعيه متبعيها الدعاء له واضافت سعيده عبر صفحتها الفايسبوكيه ان الحاله الصحيه لزوجها لازالت متدهوره حيث كتبت تعرض زوجي لحادثه سير خطيره لا يسعني الا الدعاء الدعاء الدعاء كنطلب من اله العزيز الجليل تشافيه ليا وتخليه لوليداتو عافكم كلشي يدعي معاه'

# Text Tokenization 

In [50]:
#to be used with input after training 
def clen (inp):
    text =processDoc(inp, stemmer)
    tokenizer= RegexpTokenizer(r'\w+')
    tokenized_text=tokenizer.tokenize(text) 
    stopwords_list=stopwords.words("arabic")
    remove_stop_words=[i for i in tokenized_text if not i in stopwords_list  ]
    return remove_stop_words
    
    

In [27]:
tokenizer= RegexpTokenizer(r'\w+')
clean_data ['text']=clean_data ['text'].apply(tokenizer.tokenize)

/tmp/ipykernel_13/983154222.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_data ['text']=clean_data ['text'].apply(tokenizer.tokenize)


In [28]:
clean_data.iloc[3787,0]


['اخبارنا',
 'المغربيه',
 'حنان',
 'سلامه',
 'اكدت',
 'الفنانه',
 'الصحراويه',
 'المغربيه',
 'سعيده',
 'شرف',
 'قبل',
 'قليل',
 'ان',
 'زوجها',
 'قد',
 'تعرض',
 'لحادثه',
 'سير',
 'خطيره',
 'داعيه',
 'متبعيها',
 'الدعاء',
 'له',
 'واضافت',
 'سعيده',
 'عبر',
 'صفحتها',
 'الفايسبوكيه',
 'ان',
 'الحاله',
 'الصحيه',
 'لزوجها',
 'لازالت',
 'متدهوره',
 'حيث',
 'كتبت',
 'تعرض',
 'زوجي',
 'لحادثه',
 'سير',
 'خطيره',
 'لا',
 'يسعني',
 'الا',
 'الدعاء',
 'الدعاء',
 'الدعاء',
 'كنطلب',
 'من',
 'اله',
 'العزيز',
 'الجليل',
 'تشافيه',
 'ليا',
 'وتخليه',
 'لوليداتو',
 'عافكم',
 'كلشي',
 'يدعي',
 'معاه']

In [29]:
stopwords_list=stopwords.words("arabic")
clean_data['text']= clean_data['text'].apply(lambda x: [item for item in x if item not in stopwords_list ])

/tmp/ipykernel_13/1370377237.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_data['text']= clean_data['text'].apply(lambda x: [item for item in x if item not in stopwords_list ])


# Data spliting 

In [30]:
x=clean_data["text"]
y=clean_data["targe"]



In [31]:
X_train , X_test , y_train,y_test = train_test_split(x,y,test_size=0.25,random_state =42,shuffle=True )

In [28]:
word_vec=TfidfVectorizer(sublinear_tf=True,strip_accents ='unicode',analyzer ='word',ngram_range=(1,1), max_features = 10000)

In [40]:
SVM_model= Pipeline([('tfidf',word_vec),("clf",SVC())])

In [41]:
SVM_model.fit(X_train.astype('str'),y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=10000, strip_accents='unicode',
                                 sublinear_tf=True)),
                ('clf', SVC())])

In [42]:
dump(SVM_model,'SVM_model.joblib')

['SVM_model.joblib']

In [43]:
## to load this pretrained Model
import joblib

loaded_model = joblib.load('SVM_model.joblib')
loaded_model

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=10000, strip_accents='unicode',
                                 sublinear_tf=True)),
                ('clf', SVC())])

In [44]:
y_pred = loaded_model.predict(X_test.astype('str'))
# ax = sns.histplot(y_pred, discrete=True)
# ax.set_xticklabels(["", "culture", "diverse", "economy", "politics", "sport"])

In [53]:
model_accuracy = accuracy_score(y_test,y_pred)

In [54]:
print("model_accuracy", model_accuracy)

model_accuracy 0.9606588719758806


In [ ]:
y_pred = loaded_model.predict(X_test.astype('str'))

In [ ]:
y_test.iloc[0]

In [ ]:
y_pred.iloc[0]

In [37]:
import joblib
joblib_file="/kaggle/input/racs/scikitlearn/tasvmc/1/SVM_model.joblib"
svm_model = joblib.load(joblib_file)


In [45]:
y_test.iloc[0]

4

In [58]:
l=X_test.iloc[0]
d=svm_model.predict(l)
d

array([0, 4, 3, 3, 4, 4, 4, 3, 4, 3, 3, 4, 3, 4, 4, 3, 4, 3, 4, 3, 4, 4,
       4, 0, 4, 0, 3, 4, 0, 2, 0, 0, 3, 3, 3, 3, 3, 0, 3, 3, 3, 4, 0, 4,
       0, 0, 3, 4, 0, 4, 0, 4, 4, 4, 4, 3, 4, 4, 4, 3, 3, 3, 2, 3, 0, 4,
       0, 4, 3, 0, 4, 3, 3, 3, 4, 3, 3, 3, 0, 1, 4, 2, 3, 4, 4, 0, 3, 0,
       2, 4, 2, 0, 0, 0, 3, 3, 2, 4, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 0, 0,
       4, 4, 3])

In [81]:
user_input = input()



 لا يعتزم اللاعبون المسلمون في المنتخب الفرنسي الصوم خلال شهر رمضان، لتزامنه مع بطولة «يورو 2016». وذكرت صحيفة «ليكيب» الرياضية الفرنسية، اليوم الأربعاء، أن اللاعبين المسلمين في المنتخب الفرنسي، مثل: بول بوغبا، نغولو كانتي، وباكاري سانيا، اتفقوا على ذلك مع المسؤولين في المنتخب الفرنسي.


In [82]:
# Predict sentiment
predicted_sentiments = clen(user_input)
predicted_sentiments

['يعتزم',
 'الاعبون',
 'المسلمون',
 'المنتخب',
 'الفرنسي',
 'الصوم',
 'خلال',
 'شهر',
 'رمضان',
 'لتزامنه',
 'بطوله',
 'وذكرت',
 'صحيفه',
 'ليكيب',
 'الرياضيه',
 'الفرنسيه',
 'اليوم',
 'الاربعاء',
 'ان',
 'الاعبين',
 'المسلمين',
 'المنتخب',
 'الفرنسي',
 'بول',
 'بوغبا',
 'نغولو',
 'كانتي',
 'وباكاري',
 'سانيا',
 'اتفقوا',
 'علي',
 'المسؤولين',
 'المنتخب',
 'الفرنسي']

In [83]:
acc=svm_model.predict(predicted_sentiments)
acc

array([0, 4, 3, 4, 4, 3, 2, 2, 0, 3, 4, 3, 3, 3, 4, 3, 2, 3, 3, 4, 0, 4,
       4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [59]:
o=[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]

In [60]:
model_accuracy = accuracy_score(acc,o)

In [61]:
model_accuracy

0.3235294117647059

In [62]:
y_pred = svm_model.predict(X_test.astype('str'))

In [63]:
model_accuracy = accuracy_score(y_test,y_pred)

In [78]:
   
from sklearn.metrics import f1_score
model_d1=f1_score(y_test, y_pred, average="micro")

In [79]:
model_d1

0.9606588719758806

In [65]:
y_pred

array([4, 0, 4, ..., 3, 3, 0])